spring:
    application:
        name: dawii-t1-producer

    datasource:
        url: jdbc:mysql://localhost:3306/dawii_t1
        username: root
        password: ${DB_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        
    kafka:
        bootstrap-servers: localhost:9092

app:
    rabbitmq:
        queue:
            dawii-t1-queue: DragonBall
    kafka:
        topic:
            dawii-t1-topic: DragonBall